# Dev
FROM node:22-alpine

WORKDIR /app

# Copy dependency files and install them
COPY package*.json ./
RUN npm install

# Copy the rest of your local files
COPY . .

# Expose the default port (use 5173 for Vite, 3000 for Create React App)
EXPOSE 5173

# Start the application in development mode
CMD ["npm", "run", "dev"]

