FROM node:22-alpine
WORKDIR /repo

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./
COPY backend/package.json ./backend/
COPY frontend/package.json ./frontend/

RUN yarn install

COPY frontend ./frontend

WORKDIR /repo/frontend
EXPOSE 5173
CMD ["yarn", "dev", "--host", "0.0.0.0"]

