FROM node:22-alpine
WORKDIR /repo

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./
COPY backend/package.json ./backend/
COPY frontend/package.json ./frontend/

RUN yarn install

COPY backend ./backend

WORKDIR /repo/backend
EXPOSE 3000
CMD ["yarn", "dev"]
